### ISSUE TITLE
Expected Post-Season Behavior

### ISSUE THREAD

**Issue by tracerrx** [WardBrian/mlb-led-scoreboard#11]
What should we expect for post season behavior?  Do we need to change our config if our team did not make it?  For example if I have my Preferred team set to "Yankees", And Preferred League Set to "AL East", "AL Wild Card" will it automatically show me the ALDS, ALCS, and WS games?

**Comment by WardBrian** [comment]
This depends on the status of `team_offday` for news and standings, and `only_preferred` for rotation. If you set all team offday settings to `false` and set `only_preferred` to false, it should show you all games regardless of whether or not they're on your list. 

Otherwise, yes, you will need to add any teams you want to track through the PS to your list

**Comment by tracerrx** [comment]
Thanks for the quick response... Think I will just create a new config file for postseason using the new --config option!
